ALTER TABLE channels
  ADD COLUMN IF NOT EXISTS channel_type INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bitrate_bps INTEGER NOT NULL DEFAULT 64000,
  ADD COLUMN IF NOT EXISTS opus_profile INTEGER NOT NULL DEFAULT 1;
